deploy test

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -23,7 +23,7 @@ jobs:
       - name: Build with Gradle
         run: |
           chmod +x ./gradlew
-          ./gradlew clean build -x test
+          ./gradlew clean build
 
       - name: Login to DockerHub
         uses: docker/login-action@v1
@@ -35,7 +35,7 @@ jobs:
         run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/ssaktium_server .
       - name: Push Docker
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ssaktium_server:latest
-  
+
   deploy:
     needs: build
     runs-on: ubuntu-latest
@@ -47,17 +47,20 @@ jobs:
           if [ $STATUS = 200 ]; then
             CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.SSAKTIUM_SERVER_IP }}/env")
           else
-            CURRENT_UPSTREAM=blue
+            CURRENT_UPSTREAM=green
           fi
           echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
           if [ $CURRENT_UPSTREAM = blue ]; then
             echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAM = green ]; then
+            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
             echo "STOPPED_PORT=8080" >> $GITHUB_ENV
             echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
           else
-            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
-            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+            echo "error"
+            exit 1
           fi
 
       - name: Docker compose
@@ -71,12 +74,12 @@ jobs:
             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ssaktium_server:latest
             sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
 
-#      - name: Check deploy server URL
-#        uses: jtalk/url-health-check-action@v3
-#        with:
-#          url: http://${{ secrets.SSAKTIUM_SERVER_IP }}:${{env.STOPPED_PORT}}/env
-#          max-attempts: 10
-#          retry-delay: 10s
+      - name: Check deploy server URL
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ secrets.SSAKTIUM_SERVER_IP }}:${{env.STOPPED_PORT}}/env
+          max-attempts: 6
+          retry-delay: 10s
 
       - name: Change nginx upstream
         uses: appleboy/ssh-action@master
